### ISSUE TITLE
[SwoftyWorldManager v4.0.0] Error occurred while disabling the plugin & Task #13 generated an exception

### ISSUE THREAD

**Issue by z2vvqx** [Swofty-Developments/Continued-Slime-World-Manager#20]
**Describe the issue**
I'm facing an issue where SwoftyWorldManager isn’t setting my slime-formatted "lobby" world as the main world. Even though I set the level-name in server.properties to "lobby," Minecraft still generates a standard version of the world instead of using the existing slime version. This results in conflicts, flagging the slime world as already existing when it should be the default from startup. Ideally, SwoftyWorldManager would take control and load the slime world directly without Minecraft trying to generate a normal version.

**Spigot version**
Happens in CarbonSpigot 1.8 & ImanitySpigot 1.8

**Plugin version**
v4.0.0

**How to reproduce**
Taught in the issue description

**Crash reports (if available)**
```
[14:28:38] [WARN]: [SwoftyWorldManager] Task #13 for SwoftyWorldManager v4.0.0 generated an exception
java.lang.IllegalArgumentException: World lobby already exists! Maybe it's an outdated SlimeWorld object?
	at net.swofty.swm.nms.SlimeNMS.addWorldToServerList(SlimeNMS.java:75) ~[?:?]
	at net.swofty.swm.plugin.SWMPlugin.lambda$null$2(SWMPlugin.java:295) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1051) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:958) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:848) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
```
[14:20:32] [INFO]: [SwoftyWorldManager] Disabling SwoftyWorldManager v4.0.0
[14:20:32] [ERROR]: Error occurred while disabling SwoftyWorldManager v4.0.0 (Is it up to date?)
java.util.concurrent.RejectedExecutionException: Executor has been shutdown
	at org.imanity.imanityspigot.util.n.b(SourceFile:338) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.imanity.imanityspigot.util.n$b.d(SourceFile:310) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.ImanityAsyncChunkProvider$PendingChunk.addListener(SourceFile:642) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.ImanityAsyncChunkProvider.requestChunk(SourceFile:328) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap$PlayerChunk.requestChunkIfNeeded(SourceFile:545) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap$PlayerChunk.a(SourceFile:630) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap.addPlayer(SourceFile:216) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(SourceFile:745) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport0(SourceFile:581) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(SourceFile:529) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(SourceFile:254) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.swofty.swm.nms.craft.CraftSlimeWorld.unloadWorld(CraftSlimeWorld.java:81) ~[?:?]
	at net.swofty.swm.api.world.SlimeWorld.unloadWorld(SlimeWorld.java:79) ~[?:?]
	at net.swofty.swm.plugin.SWMPlugin.lambda$onDisable$1(SWMPlugin.java:161) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.swofty.swm.plugin.SWMPlugin.onDisable(SWMPlugin.java:160) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:408) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:401) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(SourceFile:419) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(SourceFile:587) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:888) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Swofty-Developments** [comment]
Should be fixed in the latest push
